### ISSUE TITLE
new post path

### ISSUE THREAD

**Issue by asifm** [egojump/pecoup#1]
`pecoup new post` command doesn't create the correct path when in dev mode.

I'm on Windows 10. It seems the problem is related to Windows path separator ('\').

To reproduce on Windows:

```
pecoup new post "another-post"
```
creates this path in .peco/router.js
```
path: '/_posts%5Canother-post',
component: async () => {
    return import(/* webpackChunkName: "page-_posts-5Canother-post" */'dot-peco/data/_posts\another-post.md.peson')
}
```

The error in command line interface
```
ERROR in ./.peco/router.js
Module not found: Error: Can't resolve 'dot-peco/data/_postsanother-post.md.peson' in 'C:\Users\***\blog-pecoup\.peco'
 @ ./.peco/router.js 76:23-78:53
 @ ./.peco/create-app.js
 @ ./node_modules/peco/lib/engine/app/client-entry.js
 @ multi ./node_modules/peco/lib/engine/app/client-entry.js
```

(Edit: removed some unnecessary lines.)

**Comment by egoist** [comment]
does it work if you manually create `another-post.md` under `_posts` dir?

**Comment by asifm** [comment]
Same result if you manually create. For example, I created some-post.md under _posts.
```
ERROR in ./.peco/router.js
Module not found: Error: Can't resolve 'dot-peco/data/_postssome-post.md.peson' in 'C:\Users\***\blog-pecoup\.peco'
 @ ./.peco/router.js 94:23-96:50
 @ ./.peco/create-app.js
 @ ./node_modules/peco/lib/engine/app/client-entry.js
 @ multi ./node_modules/peco/lib/engine/app/client-entry.js
```

and in router.js:
```
 path: '/_posts%5Csome-post',
 component: async () => {
     return import(/* webpackChunkName: "page-_posts-5Csome-post" */'dot-peco/data/_posts\some-post.md.peson')
 }
```

**Comment by egoist** [comment]
hmm I think it's related to the [core repo](https://github.com/egojump/peco) then

**Comment by egoist** [comment]
that should be fixed in __peco__@v0.1.11 I can't confirm it though 😅

**Comment by asifm** [comment]
Thank you for looking into this so promptly. 

Something else got broken in the process. I can't now run dev server. I tried with a fresh new folder.

Below is the error after running `pecoup create firstdraft.today` and `yarn run dev`. (I confirmed it's running peco 0.1.11)

```
PS C:\Users\***\firstdraft.today> yarn run dev
yarn run v1.3.2
$ peco dev
> Building from source
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "C:/Users/***/firstdraft.today/.peco/dist/client" is not an absolute path!
   -> The output directory as **absolute path** (required).
    at webpack (C:\Users\***\firstdraft.today\node_modules\webpack\lib\webpack.js:24:9)
    at Peco.dev (C:\Users\***\firstdraft.today\node_modules\peco\lib\index.js:289:40)
    at <anonymous>
```

The directory structure after running `pecoup create firstdraft.today` and `yarn run dev`:
![image](https://user-images.githubusercontent.com/3958387/41108899-b7561568-6a43-11e8-9c9d-3a3ea1e75b3d.png)

**Comment by egoist** [comment]
Not sure what is going on there, the output path is an absolute path 😅

I'll close it here since it's unrelated to pecoup but peco itself, you may re-open the issue there to see if someone can help.

**Comment by asifm** [comment]
Sounds good. Opening a new issue in the peco repo.

**Comment by asifm** [comment]
The situation of peco@0.1.9 is not as bad as I thought. The problem occurs only if changes are made while the dev server is running. See https://github.com/egojump/peco/issues/28

The changes in peco@0.1.11 were not necessary after all.
